### ISSUE TITLE
Effects of running with LazyDFU

### ISSUE THREAD

**Issue by Madis0** [UltimateBoomer/smoothboot-fabric#38]
Smooth Boot's wiki says:

> Smooth Boot will work alongside LazyDFU.

while LazyDFU's readme says:

> LazyDFU takes a similar implementation approach to Smooth Boot: both mods do not try to modify DFU. However, LazyDFU is superior to Smooth Boot as it does not compile DFU rules at all, which is the most expensive part of the game startup process.

> In comparison, Smooth Boot will instead limit the number of threads that compile DFU rules and run them at a lower priority. 

Could you elaborate a bit more on what are the effects of running the two together. 

From my understanding, LazyDFU will make the game startup faster while Smooth Boot will continue to keep it stable afterwards by adjusting the way it is threaded. Is that correct?

**Comment by UltimateBoomer** [comment]
Basically, LazyDFU will improve the initial starting time, and Smooth Boot will make the game run smoother during parallel workloads (loading assets, generating chunks, etc).
Smooth Boot improves the initial loading speed by making DFU run with a lower number of threads and at a lower priority, so that the main threads used for loading can take up more CPU time. LazyDFU prevents DFU from initializing at startup altogether. So if you have LazyDFU installed, Smooth Boot will not improve loading times much further.
The other use of Smooth Boot is for changing thread priority and the number of threads Minecraft uses for parallel workloads. This is useful when Minecraft is pegging the CPU to 100% and slowing down other programs. In these situations, reducing the thread count and thread priority will make Minecraft take up less CPU. It could also reduce stuttering during gameplay if less CPU time is stolen from the main thread during these workloads.

**Comment by Madis0** [comment]
Thank you!
